---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
#    - role: raspberrypi
    - role: comfort

- hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: tools

- hosts: node
  become: yes
  roles:
    - role: k3s/node
