# This code is from https://github.com/gantsign/ansible_role_helm/blob/master/tasks/main.yml
---
# The OS of the Helm redistributable
helm_os: 'linux'

# File name of the Helm redistributable file
helm_redis_filename: 'helm-v{{ helm_version }}-{{ helm_os }}-{{ helm_architecture }}.tar.gz'

# Helm version number
helm_version: '3.7.1'

# The CPU architecture of the Helm executable to install
helm_architecture: 'amd64'

# Mirror to download Helm from
helm_mirror: 'https://get.helm.sh'

# Dir where Helm should be installed
helm_install_dir: '/usr/local/share/helm'

# Directory to store files downloaded for Helm
helm_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"

