---

- name: create .bash_aliases
  file:
    path: ~/.bash_aliases
    state: touch
    mode: 644
  tags:
    - comfort
    - comfort.bash

- name: copy ~/.k8s_aliases
  copy:
    dest: ~/.k8s_aliases
    content: >-
      {{ lookup("template", "k8s_aliases") }}
  tags:
    - comfort
    - comfort.alias

- name: Load ~/.k8s_aliases from .bash_aliases
  lineinfile:
    line: "source ~/.k8s_aliases"
    state: present
    insertafter: EOF
    path: ~/.bash_aliases
  tags:
    - comfort
    - comfort.alias

# https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/
- name: install bash-completion
  ansible.builtin.package:
    name: bash-completion
    state: present
  when: "'master' in group_names"
  tags:
    - comfort
    - comfort.completion

- name: test kubectl completion
  ansible.builtin.stat: 
    path: /etc/bash_completion.d/kubectl
  register: test_kubectl_completion
  when: "'master' in group_names"
  tags:
    - comfort
    - comfort.completion

- name: kubectl completion bash
  ansible.builtin.shell: "kubectl completion bash > /etc/bash_completion.d/kubectl"
  when:
    - ( test_kubectl_completion.stat.exists is false and
      'master' in group_names )
  tags:
    - comfort
    - comfort.completion

- name: extend shell completion to work with aliases
  lineinfile:
    line: "{{ item }}"
    state: present
    insertafter: EOF
    path: ~/.bashrc
  with_items:
    - "complete -F __start_kubectl k"
    - "complete -F __start_kubectl kc"
  when:
    - ( test_kubectl_completion.stat.exists is false and
      'master' in group_names )
  tags:
    - comfort
    - comfort.alias
