---

- name: .bash_aliases
  file:
    path: ~/.bash_aliases
    state: touch
    mode: 644
  tags:
    - comfort
    - comfort.bash

- name: populate .bash_aliases
  lineinfile:
    line: "{{ item }}"
    state: present
    insertafter: EOF
    path: ~/.bash_aliases
  with_items:
    - "alias k=kubectl"
    - "alias kaf='kubectl apply -f'"
    - "alias kc=kubectl"
    - "alias kca='_kca(){ kubectl \"$@\" --all-namespaces;  unset -f _kca; }; _kca'"
    - "alias kccc='kubectl config current-context'"
    - "alias kcdc='kubectl config delete-context'"
    - "alias kcgc='kubectl config get-contexts'"
    - "alias kcn='kubectl config set-context --current --namespace'"
    - "alias kcp='kubectl cp'"
    - "alias kcsc='kubectl config set-context'"
    - "alias kcuc='kubectl config use-context'"
    - "alias kdcj='kubectl describe cronjob'"
    - "alias kdcm='kubectl describe configmap'"
    - "alias kdd='kubectl describe deployment'"
    - "alias kdds='kubectl describe daemonset'"
    - "alias kdel='kubectl delete'"
    - "alias kdelcj='kubectl delete cronjob'"
    - "alias kdelcm='kubectl delete configmap'"
    - "alias kdeld='kubectl delete deployment'"
    - "alias kdelds='kubectl delete daemonset'"
    - "alias kdelf='kubectl delete -f'"
    - "alias kdeli='kubectl delete ingress'"
    - "alias kdelno='kubectl delete node'"
    - "alias kdelns='kubectl delete namespace'"
    - "alias kdelp='kubectl delete pods'"
    - "alias kdelpvc='kubectl delete pvc'"
    - "alias kdels='kubectl delete svc'"
    - "alias kdelsa='kubectl delete sa'"
    - "alias kdelsec='kubectl delete secret'"
    - "alias kdelss='kubectl delete statefulset'"
    - "alias kdi='kubectl describe ingress'"
    - "alias kdno='kubectl describe node'"
    - "alias kdns='kubectl describe namespace'"
    - "alias kdp='kubectl describe pods'"
    - "alias kdpvc='kubectl describe pvc'"
    - "alias kds='kubectl describe svc'"
    - "alias kdsa='kubectl describe sa'"
    - "alias kdsec='kubectl describe secret'"
    - "alias kdss='kubectl describe statefulset'"
    - "alias kecj='kubectl edit cronjob'"
    - "alias kecm='kubectl edit configmap'"
    - "alias ked='kubectl edit deployment'"
    - "alias keds='kubectl edit daemonset'"
    - "alias kei='kubectl edit ingress'"
    - "alias keno='kubectl edit node'"
    - "alias kens='kubectl edit namespace'"
    - "alias kep='kubectl edit pods'"
    - "alias kepvc='kubectl edit pvc'"
    - "alias kes='kubectl edit svc'"
    - "alias kess='kubectl edit statefulset'"
    - "alias keti='kubectl exec -ti'"
    - "alias kga='kubectl get all'"
    - "alias kgaa='kubectl get all --all-namespaces'"
    - "alias kgcj='kubectl get cronjob'"
    - "alias kgcm='kubectl get configmaps'"
    - "alias kgcma='kubectl get configmaps --all-namespaces'"
    - "alias kgd='kubectl get deployment'"
    - "alias kgda='kubectl get deployment --all-namespaces'"
    - "alias kgds='kubectl get daemonset'"
    - "alias kgi='kubectl get ingress'"
    - "alias kgia='kubectl get ingress --all-namespaces'"
    - "alias kgno='kubectl get nodes'"
    - "alias kgns='kubectl get namespaces'"
    - "alias kgp='kubectl get pods -o wide'"
    - "alias kgpa='kubectl get pods --all-namespaces'"
    - "alias kgpall='kubectl get pods --all-namespaces -o wide'"
    - "alias kgpvc='kubectl get pvc'"
    - "alias kgpvca='kubectl get pvc --all-namespaces'"
    - "alias kgrs='kubectl get rs'"
    - "alias kgs='kubectl get svc'"
    - "alias kgsa='kubectl get svc --all-namespaces'"
    - "alias kgsec='kubectl get secret'"
    - "alias kgseca='kubectl get secret --all-namespaces'"
    - "alias kgss='kubectl get statefulset'"
    - "alias kgssa='kubectl get statefulset --all-namespaces'"
    - "alias kl='kubectl logs'"
    - "alias kl1h='kubectl logs --since 1h'"
    - "alias kl1m='kubectl logs --since 1m'"
    - "alias kl1s='kubectl logs --since 1s'"
    - "alias klf='kubectl logs -f'"
    - "alias klf1h='kubectl logs --since 1h -f'"
    - "alias klf1m='kubectl logs --since 1m -f'"
    - "alias klf1s='kubectl logs --since 1s -f'"
    - "alias kpf='kubectl port-forward'"
    - "alias krh='kubectl rollout history'"
    - "alias krsd='kubectl rollout status deployment'"
    - "alias krsss='kubectl rollout status statefulset'"
    - "alias kru='kubectl rollout undo'"
    - "alias ksd='kubectl scale deployment'"
    - "alias ksss='kubectl scale statefulset'"
  tags:
    - comfort
    - comfort.alias

# https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/
- name: install bash-completion
  ansible.builtin.package:
    name: bash-completion
    state: present
  when: "'master' in group_names"
  tags:
    - comfort
    - comfort.completion

- name: test kubectl completion
  ansible.builtin.stat: 
    path: /etc/bash_completion.d/kubectl
  register: test_kubectl_completion
  when: "'master' in group_names"
  tags:
    - comfort
    - comfort.completion

- name: kubectl completion bash
  ansible.builtin.shell: "kubectl completion bash > /etc/bash_completion.d/kubectl"
  when:
    - ( test_kubectl_completion.stat.exists is false and
      'master' in group_names )
  tags:
    - comfort
    - comfort.completion

- name: extend shell completion to work with aliases
  lineinfile:
    line: "{{ item }}"
    state: present
    insertafter: EOF
    path: ~/.bashrc
  with_items:
    - "complete -F __start_kubectl k"
    - "complete -F __start_kubectl kc"
  when:
    - ( test_kubectl_completion.stat.exists is false and
      'master' in group_names )
  tags:
    - comfort
    - comfort.alias
