# Who Let The Pods Out? — https://k9scli.io/
# K9s provides a terminal UI to interact with your Kubernetes clusters.
---
- name: check k9s
  ansible.builtin.shell:
    cmd: k9s version -s || true
  register: _k9s
  changed_when: False
  tags:
    - tools
    - tools.k9s

- name: download k9s
  get_url:
    url: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_x86_64.tar.gz
    dest: /tmp/k9s_Linux_x86_64.tar.gz
  when: "'Version' not in _k9s.stdout"
  tags:
    - tools
    - tools.k9s

- name: extract k9s_Linux_x86_64.tar.gz into /usr/bin
  ansible.builtin.shell:
    cmd: tar xzf /tmp/k9s_Linux_x86_64.tar.gz k9s
    chdir: /usr/bin/
  when: "'Version' not in _k9s.stdout"
  tags:
    - tools
    - tools.k9s
